apiVersion: apps/v1
 # The type of workload we are creating 
kind: Deployment
metadata:
  # Name of deployment - Required
  name: vijay-portfolio 
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: vijay-portfolio
  # Pod template which decribes the pod you want to deploy
  template: 
    metadata:
      # Used to logically group pods together
      labels: 
        app: vijay-portfolio
    # Specific details about the containers in the Pod
    spec: 
      containers:
      - name: vijay-portfolio-container
        # Docker Hub image to use
        image: amviacrdev.azurecr.io/vijay-portfolio-amvi:419e4e30bfb632cb2cc1d03d773f91f8d6f52dcb
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 5002
          # Reference name of port
          name: http 
        resources:
          # Minimum amount of resources we want
          requests: 
            cpu: 100m
            memory: 128Mi
          # Maximum amount of resources we want
          limits: 
            cpu: 250m
            memory: 256Mi