# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: My Portfolio

#on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

env:
  IMAGE_NAME: vijay-portfolio-amvi # Replace 'your-image-name' with the name you want for your Docker image
  REGISTRY: amviacrdev.azurecr.io # Replace 'your-acr-name' with your Azure Container Registry name
  REGISTRY_USERNAME: amviacrdev # Replace 'your-acr-username' with the ACR username
  REGISTRY_PASSWORD: ${{ secrets.ACR_PASSWORD }} # Add your ACR access key as a GitHub secret in the repository settings

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
     name: Login to Azure Container Registry
      run: docker login ${{ env.REGISTRY }} -u ${{ env.REGISTRY_USERNAME }} -p ${{ env.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    #- name: run app
    #  run: python app.py
      
    #- name: Test with pytest
    #  run: |
    #    pytest
